import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { FinancialTransactionOrderByWithRelationInputObjectSchema as FinancialTransactionOrderByWithRelationInputObjectSchema } from './objects/FinancialTransactionOrderByWithRelationInput.schema';
import { FinancialTransactionWhereInputObjectSchema as FinancialTransactionWhereInputObjectSchema } from './objects/FinancialTransactionWhereInput.schema';
import { FinancialTransactionWhereUniqueInputObjectSchema as FinancialTransactionWhereUniqueInputObjectSchema } from './objects/FinancialTransactionWhereUniqueInput.schema';
import { FinancialTransactionCountAggregateInputObjectSchema as FinancialTransactionCountAggregateInputObjectSchema } from './objects/FinancialTransactionCountAggregateInput.schema';
import { FinancialTransactionMinAggregateInputObjectSchema as FinancialTransactionMinAggregateInputObjectSchema } from './objects/FinancialTransactionMinAggregateInput.schema';
import { FinancialTransactionMaxAggregateInputObjectSchema as FinancialTransactionMaxAggregateInputObjectSchema } from './objects/FinancialTransactionMaxAggregateInput.schema';
import { FinancialTransactionAvgAggregateInputObjectSchema as FinancialTransactionAvgAggregateInputObjectSchema } from './objects/FinancialTransactionAvgAggregateInput.schema';
import { FinancialTransactionSumAggregateInputObjectSchema as FinancialTransactionSumAggregateInputObjectSchema } from './objects/FinancialTransactionSumAggregateInput.schema';

export const FinancialTransactionAggregateSchema: z.ZodType<Prisma.FinancialTransactionAggregateArgs> = z.object({ orderBy: z.union([FinancialTransactionOrderByWithRelationInputObjectSchema, FinancialTransactionOrderByWithRelationInputObjectSchema.array()]).optional(), where: FinancialTransactionWhereInputObjectSchema.optional(), cursor: FinancialTransactionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), FinancialTransactionCountAggregateInputObjectSchema ]).optional(), _min: FinancialTransactionMinAggregateInputObjectSchema.optional(), _max: FinancialTransactionMaxAggregateInputObjectSchema.optional(), _avg: FinancialTransactionAvgAggregateInputObjectSchema.optional(), _sum: FinancialTransactionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.FinancialTransactionAggregateArgs>;

export const FinancialTransactionAggregateZodSchema = z.object({ orderBy: z.union([FinancialTransactionOrderByWithRelationInputObjectSchema, FinancialTransactionOrderByWithRelationInputObjectSchema.array()]).optional(), where: FinancialTransactionWhereInputObjectSchema.optional(), cursor: FinancialTransactionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), FinancialTransactionCountAggregateInputObjectSchema ]).optional(), _min: FinancialTransactionMinAggregateInputObjectSchema.optional(), _max: FinancialTransactionMaxAggregateInputObjectSchema.optional(), _avg: FinancialTransactionAvgAggregateInputObjectSchema.optional(), _sum: FinancialTransactionSumAggregateInputObjectSchema.optional() }).strict();