import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { SaasMetricsOrderByWithRelationInputObjectSchema as SaasMetricsOrderByWithRelationInputObjectSchema } from './objects/SaasMetricsOrderByWithRelationInput.schema';
import { SaasMetricsWhereInputObjectSchema as SaasMetricsWhereInputObjectSchema } from './objects/SaasMetricsWhereInput.schema';
import { SaasMetricsWhereUniqueInputObjectSchema as SaasMetricsWhereUniqueInputObjectSchema } from './objects/SaasMetricsWhereUniqueInput.schema';
import { SaasMetricsCountAggregateInputObjectSchema as SaasMetricsCountAggregateInputObjectSchema } from './objects/SaasMetricsCountAggregateInput.schema';
import { SaasMetricsMinAggregateInputObjectSchema as SaasMetricsMinAggregateInputObjectSchema } from './objects/SaasMetricsMinAggregateInput.schema';
import { SaasMetricsMaxAggregateInputObjectSchema as SaasMetricsMaxAggregateInputObjectSchema } from './objects/SaasMetricsMaxAggregateInput.schema';
import { SaasMetricsAvgAggregateInputObjectSchema as SaasMetricsAvgAggregateInputObjectSchema } from './objects/SaasMetricsAvgAggregateInput.schema';
import { SaasMetricsSumAggregateInputObjectSchema as SaasMetricsSumAggregateInputObjectSchema } from './objects/SaasMetricsSumAggregateInput.schema';

export const SaasMetricsAggregateSchema: z.ZodType<Prisma.SaasMetricsAggregateArgs> = z.object({ orderBy: z.union([SaasMetricsOrderByWithRelationInputObjectSchema, SaasMetricsOrderByWithRelationInputObjectSchema.array()]).optional(), where: SaasMetricsWhereInputObjectSchema.optional(), cursor: SaasMetricsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SaasMetricsCountAggregateInputObjectSchema ]).optional(), _min: SaasMetricsMinAggregateInputObjectSchema.optional(), _max: SaasMetricsMaxAggregateInputObjectSchema.optional(), _avg: SaasMetricsAvgAggregateInputObjectSchema.optional(), _sum: SaasMetricsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SaasMetricsAggregateArgs>;

export const SaasMetricsAggregateZodSchema = z.object({ orderBy: z.union([SaasMetricsOrderByWithRelationInputObjectSchema, SaasMetricsOrderByWithRelationInputObjectSchema.array()]).optional(), where: SaasMetricsWhereInputObjectSchema.optional(), cursor: SaasMetricsWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SaasMetricsCountAggregateInputObjectSchema ]).optional(), _min: SaasMetricsMinAggregateInputObjectSchema.optional(), _max: SaasMetricsMaxAggregateInputObjectSchema.optional(), _avg: SaasMetricsAvgAggregateInputObjectSchema.optional(), _sum: SaasMetricsSumAggregateInputObjectSchema.optional() }).strict();