import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { CostTrackingOrderByWithRelationInputObjectSchema as CostTrackingOrderByWithRelationInputObjectSchema } from './objects/CostTrackingOrderByWithRelationInput.schema';
import { CostTrackingWhereInputObjectSchema as CostTrackingWhereInputObjectSchema } from './objects/CostTrackingWhereInput.schema';
import { CostTrackingWhereUniqueInputObjectSchema as CostTrackingWhereUniqueInputObjectSchema } from './objects/CostTrackingWhereUniqueInput.schema';
import { CostTrackingCountAggregateInputObjectSchema as CostTrackingCountAggregateInputObjectSchema } from './objects/CostTrackingCountAggregateInput.schema';
import { CostTrackingMinAggregateInputObjectSchema as CostTrackingMinAggregateInputObjectSchema } from './objects/CostTrackingMinAggregateInput.schema';
import { CostTrackingMaxAggregateInputObjectSchema as CostTrackingMaxAggregateInputObjectSchema } from './objects/CostTrackingMaxAggregateInput.schema';
import { CostTrackingAvgAggregateInputObjectSchema as CostTrackingAvgAggregateInputObjectSchema } from './objects/CostTrackingAvgAggregateInput.schema';
import { CostTrackingSumAggregateInputObjectSchema as CostTrackingSumAggregateInputObjectSchema } from './objects/CostTrackingSumAggregateInput.schema';

export const CostTrackingAggregateSchema: z.ZodType<Prisma.CostTrackingAggregateArgs> = z.object({ orderBy: z.union([CostTrackingOrderByWithRelationInputObjectSchema, CostTrackingOrderByWithRelationInputObjectSchema.array()]).optional(), where: CostTrackingWhereInputObjectSchema.optional(), cursor: CostTrackingWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CostTrackingCountAggregateInputObjectSchema ]).optional(), _min: CostTrackingMinAggregateInputObjectSchema.optional(), _max: CostTrackingMaxAggregateInputObjectSchema.optional(), _avg: CostTrackingAvgAggregateInputObjectSchema.optional(), _sum: CostTrackingSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CostTrackingAggregateArgs>;

export const CostTrackingAggregateZodSchema = z.object({ orderBy: z.union([CostTrackingOrderByWithRelationInputObjectSchema, CostTrackingOrderByWithRelationInputObjectSchema.array()]).optional(), where: CostTrackingWhereInputObjectSchema.optional(), cursor: CostTrackingWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), CostTrackingCountAggregateInputObjectSchema ]).optional(), _min: CostTrackingMinAggregateInputObjectSchema.optional(), _max: CostTrackingMaxAggregateInputObjectSchema.optional(), _avg: CostTrackingAvgAggregateInputObjectSchema.optional(), _sum: CostTrackingSumAggregateInputObjectSchema.optional() }).strict();