import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { AgentDecisionOrderByWithRelationInputObjectSchema as AgentDecisionOrderByWithRelationInputObjectSchema } from './objects/AgentDecisionOrderByWithRelationInput.schema';
import { AgentDecisionWhereInputObjectSchema as AgentDecisionWhereInputObjectSchema } from './objects/AgentDecisionWhereInput.schema';
import { AgentDecisionWhereUniqueInputObjectSchema as AgentDecisionWhereUniqueInputObjectSchema } from './objects/AgentDecisionWhereUniqueInput.schema';
import { AgentDecisionCountAggregateInputObjectSchema as AgentDecisionCountAggregateInputObjectSchema } from './objects/AgentDecisionCountAggregateInput.schema';
import { AgentDecisionMinAggregateInputObjectSchema as AgentDecisionMinAggregateInputObjectSchema } from './objects/AgentDecisionMinAggregateInput.schema';
import { AgentDecisionMaxAggregateInputObjectSchema as AgentDecisionMaxAggregateInputObjectSchema } from './objects/AgentDecisionMaxAggregateInput.schema';

export const AgentDecisionAggregateSchema: z.ZodType<Prisma.AgentDecisionAggregateArgs> = z.object({ orderBy: z.union([AgentDecisionOrderByWithRelationInputObjectSchema, AgentDecisionOrderByWithRelationInputObjectSchema.array()]).optional(), where: AgentDecisionWhereInputObjectSchema.optional(), cursor: AgentDecisionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AgentDecisionCountAggregateInputObjectSchema ]).optional(), _min: AgentDecisionMinAggregateInputObjectSchema.optional(), _max: AgentDecisionMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgentDecisionAggregateArgs>;

export const AgentDecisionAggregateZodSchema = z.object({ orderBy: z.union([AgentDecisionOrderByWithRelationInputObjectSchema, AgentDecisionOrderByWithRelationInputObjectSchema.array()]).optional(), where: AgentDecisionWhereInputObjectSchema.optional(), cursor: AgentDecisionWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), AgentDecisionCountAggregateInputObjectSchema ]).optional(), _min: AgentDecisionMinAggregateInputObjectSchema.optional(), _max: AgentDecisionMaxAggregateInputObjectSchema.optional() }).strict();