import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { CostTrackingWhereInputObjectSchema as CostTrackingWhereInputObjectSchema } from './objects/CostTrackingWhereInput.schema';
import { CostTrackingOrderByWithAggregationInputObjectSchema as CostTrackingOrderByWithAggregationInputObjectSchema } from './objects/CostTrackingOrderByWithAggregationInput.schema';
import { CostTrackingScalarWhereWithAggregatesInputObjectSchema as CostTrackingScalarWhereWithAggregatesInputObjectSchema } from './objects/CostTrackingScalarWhereWithAggregatesInput.schema';
import { CostTrackingScalarFieldEnumSchema } from './enums/CostTrackingScalarFieldEnum.schema';
import { CostTrackingCountAggregateInputObjectSchema as CostTrackingCountAggregateInputObjectSchema } from './objects/CostTrackingCountAggregateInput.schema';
import { CostTrackingMinAggregateInputObjectSchema as CostTrackingMinAggregateInputObjectSchema } from './objects/CostTrackingMinAggregateInput.schema';
import { CostTrackingMaxAggregateInputObjectSchema as CostTrackingMaxAggregateInputObjectSchema } from './objects/CostTrackingMaxAggregateInput.schema';
import { CostTrackingAvgAggregateInputObjectSchema as CostTrackingAvgAggregateInputObjectSchema } from './objects/CostTrackingAvgAggregateInput.schema';
import { CostTrackingSumAggregateInputObjectSchema as CostTrackingSumAggregateInputObjectSchema } from './objects/CostTrackingSumAggregateInput.schema';

export const CostTrackingGroupBySchema: z.ZodType<Prisma.CostTrackingGroupByArgs> = z.object({ where: CostTrackingWhereInputObjectSchema.optional(), orderBy: z.union([CostTrackingOrderByWithAggregationInputObjectSchema, CostTrackingOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CostTrackingScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CostTrackingScalarFieldEnumSchema), _count: z.union([ z.literal(true), CostTrackingCountAggregateInputObjectSchema ]).optional(), _min: CostTrackingMinAggregateInputObjectSchema.optional(), _max: CostTrackingMaxAggregateInputObjectSchema.optional(), _avg: CostTrackingAvgAggregateInputObjectSchema.optional(), _sum: CostTrackingSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.CostTrackingGroupByArgs>;

export const CostTrackingGroupByZodSchema = z.object({ where: CostTrackingWhereInputObjectSchema.optional(), orderBy: z.union([CostTrackingOrderByWithAggregationInputObjectSchema, CostTrackingOrderByWithAggregationInputObjectSchema.array()]).optional(), having: CostTrackingScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(CostTrackingScalarFieldEnumSchema), _count: z.union([ z.literal(true), CostTrackingCountAggregateInputObjectSchema ]).optional(), _min: CostTrackingMinAggregateInputObjectSchema.optional(), _max: CostTrackingMaxAggregateInputObjectSchema.optional(), _avg: CostTrackingAvgAggregateInputObjectSchema.optional(), _sum: CostTrackingSumAggregateInputObjectSchema.optional() }).strict();