import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { PasskeyWhereInputObjectSchema as PasskeyWhereInputObjectSchema } from './objects/PasskeyWhereInput.schema';
import { PasskeyOrderByWithAggregationInputObjectSchema as PasskeyOrderByWithAggregationInputObjectSchema } from './objects/PasskeyOrderByWithAggregationInput.schema';
import { PasskeyScalarWhereWithAggregatesInputObjectSchema as PasskeyScalarWhereWithAggregatesInputObjectSchema } from './objects/PasskeyScalarWhereWithAggregatesInput.schema';
import { PasskeyScalarFieldEnumSchema } from './enums/PasskeyScalarFieldEnum.schema';
import { PasskeyCountAggregateInputObjectSchema as PasskeyCountAggregateInputObjectSchema } from './objects/PasskeyCountAggregateInput.schema';
import { PasskeyMinAggregateInputObjectSchema as PasskeyMinAggregateInputObjectSchema } from './objects/PasskeyMinAggregateInput.schema';
import { PasskeyMaxAggregateInputObjectSchema as PasskeyMaxAggregateInputObjectSchema } from './objects/PasskeyMaxAggregateInput.schema';
import { PasskeyAvgAggregateInputObjectSchema as PasskeyAvgAggregateInputObjectSchema } from './objects/PasskeyAvgAggregateInput.schema';
import { PasskeySumAggregateInputObjectSchema as PasskeySumAggregateInputObjectSchema } from './objects/PasskeySumAggregateInput.schema';

export const PasskeyGroupBySchema: z.ZodType<Prisma.PasskeyGroupByArgs> = z.object({ where: PasskeyWhereInputObjectSchema.optional(), orderBy: z.union([PasskeyOrderByWithAggregationInputObjectSchema, PasskeyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PasskeyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PasskeyScalarFieldEnumSchema), _count: z.union([ z.literal(true), PasskeyCountAggregateInputObjectSchema ]).optional(), _min: PasskeyMinAggregateInputObjectSchema.optional(), _max: PasskeyMaxAggregateInputObjectSchema.optional(), _avg: PasskeyAvgAggregateInputObjectSchema.optional(), _sum: PasskeySumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PasskeyGroupByArgs>;

export const PasskeyGroupByZodSchema = z.object({ where: PasskeyWhereInputObjectSchema.optional(), orderBy: z.union([PasskeyOrderByWithAggregationInputObjectSchema, PasskeyOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PasskeyScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PasskeyScalarFieldEnumSchema), _count: z.union([ z.literal(true), PasskeyCountAggregateInputObjectSchema ]).optional(), _min: PasskeyMinAggregateInputObjectSchema.optional(), _max: PasskeyMaxAggregateInputObjectSchema.optional(), _avg: PasskeyAvgAggregateInputObjectSchema.optional(), _sum: PasskeySumAggregateInputObjectSchema.optional() }).strict();