import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { SaasMetricsWhereInputObjectSchema as SaasMetricsWhereInputObjectSchema } from './objects/SaasMetricsWhereInput.schema';
import { SaasMetricsOrderByWithAggregationInputObjectSchema as SaasMetricsOrderByWithAggregationInputObjectSchema } from './objects/SaasMetricsOrderByWithAggregationInput.schema';
import { SaasMetricsScalarWhereWithAggregatesInputObjectSchema as SaasMetricsScalarWhereWithAggregatesInputObjectSchema } from './objects/SaasMetricsScalarWhereWithAggregatesInput.schema';
import { SaasMetricsScalarFieldEnumSchema } from './enums/SaasMetricsScalarFieldEnum.schema';
import { SaasMetricsCountAggregateInputObjectSchema as SaasMetricsCountAggregateInputObjectSchema } from './objects/SaasMetricsCountAggregateInput.schema';
import { SaasMetricsMinAggregateInputObjectSchema as SaasMetricsMinAggregateInputObjectSchema } from './objects/SaasMetricsMinAggregateInput.schema';
import { SaasMetricsMaxAggregateInputObjectSchema as SaasMetricsMaxAggregateInputObjectSchema } from './objects/SaasMetricsMaxAggregateInput.schema';
import { SaasMetricsAvgAggregateInputObjectSchema as SaasMetricsAvgAggregateInputObjectSchema } from './objects/SaasMetricsAvgAggregateInput.schema';
import { SaasMetricsSumAggregateInputObjectSchema as SaasMetricsSumAggregateInputObjectSchema } from './objects/SaasMetricsSumAggregateInput.schema';

export const SaasMetricsGroupBySchema: z.ZodType<Prisma.SaasMetricsGroupByArgs> = z.object({ where: SaasMetricsWhereInputObjectSchema.optional(), orderBy: z.union([SaasMetricsOrderByWithAggregationInputObjectSchema, SaasMetricsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SaasMetricsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SaasMetricsScalarFieldEnumSchema), _count: z.union([ z.literal(true), SaasMetricsCountAggregateInputObjectSchema ]).optional(), _min: SaasMetricsMinAggregateInputObjectSchema.optional(), _max: SaasMetricsMaxAggregateInputObjectSchema.optional(), _avg: SaasMetricsAvgAggregateInputObjectSchema.optional(), _sum: SaasMetricsSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SaasMetricsGroupByArgs>;

export const SaasMetricsGroupByZodSchema = z.object({ where: SaasMetricsWhereInputObjectSchema.optional(), orderBy: z.union([SaasMetricsOrderByWithAggregationInputObjectSchema, SaasMetricsOrderByWithAggregationInputObjectSchema.array()]).optional(), having: SaasMetricsScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(SaasMetricsScalarFieldEnumSchema), _count: z.union([ z.literal(true), SaasMetricsCountAggregateInputObjectSchema ]).optional(), _min: SaasMetricsMinAggregateInputObjectSchema.optional(), _max: SaasMetricsMaxAggregateInputObjectSchema.optional(), _avg: SaasMetricsAvgAggregateInputObjectSchema.optional(), _sum: SaasMetricsSumAggregateInputObjectSchema.optional() }).strict();