import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { AgentDecisionWhereInputObjectSchema as AgentDecisionWhereInputObjectSchema } from './objects/AgentDecisionWhereInput.schema';
import { AgentDecisionOrderByWithAggregationInputObjectSchema as AgentDecisionOrderByWithAggregationInputObjectSchema } from './objects/AgentDecisionOrderByWithAggregationInput.schema';
import { AgentDecisionScalarWhereWithAggregatesInputObjectSchema as AgentDecisionScalarWhereWithAggregatesInputObjectSchema } from './objects/AgentDecisionScalarWhereWithAggregatesInput.schema';
import { AgentDecisionScalarFieldEnumSchema } from './enums/AgentDecisionScalarFieldEnum.schema';
import { AgentDecisionCountAggregateInputObjectSchema as AgentDecisionCountAggregateInputObjectSchema } from './objects/AgentDecisionCountAggregateInput.schema';
import { AgentDecisionMinAggregateInputObjectSchema as AgentDecisionMinAggregateInputObjectSchema } from './objects/AgentDecisionMinAggregateInput.schema';
import { AgentDecisionMaxAggregateInputObjectSchema as AgentDecisionMaxAggregateInputObjectSchema } from './objects/AgentDecisionMaxAggregateInput.schema';

export const AgentDecisionGroupBySchema: z.ZodType<Prisma.AgentDecisionGroupByArgs> = z.object({ where: AgentDecisionWhereInputObjectSchema.optional(), orderBy: z.union([AgentDecisionOrderByWithAggregationInputObjectSchema, AgentDecisionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgentDecisionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgentDecisionScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgentDecisionCountAggregateInputObjectSchema ]).optional(), _min: AgentDecisionMinAggregateInputObjectSchema.optional(), _max: AgentDecisionMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.AgentDecisionGroupByArgs>;

export const AgentDecisionGroupByZodSchema = z.object({ where: AgentDecisionWhereInputObjectSchema.optional(), orderBy: z.union([AgentDecisionOrderByWithAggregationInputObjectSchema, AgentDecisionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: AgentDecisionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(AgentDecisionScalarFieldEnumSchema), _count: z.union([ z.literal(true), AgentDecisionCountAggregateInputObjectSchema ]).optional(), _min: AgentDecisionMinAggregateInputObjectSchema.optional(), _max: AgentDecisionMaxAggregateInputObjectSchema.optional() }).strict();