import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { PurchaseWhereInputObjectSchema as PurchaseWhereInputObjectSchema } from './objects/PurchaseWhereInput.schema';
import { PurchaseOrderByWithAggregationInputObjectSchema as PurchaseOrderByWithAggregationInputObjectSchema } from './objects/PurchaseOrderByWithAggregationInput.schema';
import { PurchaseScalarWhereWithAggregatesInputObjectSchema as PurchaseScalarWhereWithAggregatesInputObjectSchema } from './objects/PurchaseScalarWhereWithAggregatesInput.schema';
import { PurchaseScalarFieldEnumSchema } from './enums/PurchaseScalarFieldEnum.schema';
import { PurchaseCountAggregateInputObjectSchema as PurchaseCountAggregateInputObjectSchema } from './objects/PurchaseCountAggregateInput.schema';
import { PurchaseMinAggregateInputObjectSchema as PurchaseMinAggregateInputObjectSchema } from './objects/PurchaseMinAggregateInput.schema';
import { PurchaseMaxAggregateInputObjectSchema as PurchaseMaxAggregateInputObjectSchema } from './objects/PurchaseMaxAggregateInput.schema';

export const PurchaseGroupBySchema: z.ZodType<Prisma.PurchaseGroupByArgs> = z.object({ where: PurchaseWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseOrderByWithAggregationInputObjectSchema, PurchaseOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseCountAggregateInputObjectSchema ]).optional(), _min: PurchaseMinAggregateInputObjectSchema.optional(), _max: PurchaseMaxAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.PurchaseGroupByArgs>;

export const PurchaseGroupByZodSchema = z.object({ where: PurchaseWhereInputObjectSchema.optional(), orderBy: z.union([PurchaseOrderByWithAggregationInputObjectSchema, PurchaseOrderByWithAggregationInputObjectSchema.array()]).optional(), having: PurchaseScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(PurchaseScalarFieldEnumSchema), _count: z.union([ z.literal(true), PurchaseCountAggregateInputObjectSchema ]).optional(), _min: PurchaseMinAggregateInputObjectSchema.optional(), _max: PurchaseMaxAggregateInputObjectSchema.optional() }).strict();