import type { Prisma } from '../../generated/client';
import * as z from 'zod';
import { FinancialTransactionWhereInputObjectSchema as FinancialTransactionWhereInputObjectSchema } from './objects/FinancialTransactionWhereInput.schema';
import { FinancialTransactionOrderByWithAggregationInputObjectSchema as FinancialTransactionOrderByWithAggregationInputObjectSchema } from './objects/FinancialTransactionOrderByWithAggregationInput.schema';
import { FinancialTransactionScalarWhereWithAggregatesInputObjectSchema as FinancialTransactionScalarWhereWithAggregatesInputObjectSchema } from './objects/FinancialTransactionScalarWhereWithAggregatesInput.schema';
import { FinancialTransactionScalarFieldEnumSchema } from './enums/FinancialTransactionScalarFieldEnum.schema';
import { FinancialTransactionCountAggregateInputObjectSchema as FinancialTransactionCountAggregateInputObjectSchema } from './objects/FinancialTransactionCountAggregateInput.schema';
import { FinancialTransactionMinAggregateInputObjectSchema as FinancialTransactionMinAggregateInputObjectSchema } from './objects/FinancialTransactionMinAggregateInput.schema';
import { FinancialTransactionMaxAggregateInputObjectSchema as FinancialTransactionMaxAggregateInputObjectSchema } from './objects/FinancialTransactionMaxAggregateInput.schema';
import { FinancialTransactionAvgAggregateInputObjectSchema as FinancialTransactionAvgAggregateInputObjectSchema } from './objects/FinancialTransactionAvgAggregateInput.schema';
import { FinancialTransactionSumAggregateInputObjectSchema as FinancialTransactionSumAggregateInputObjectSchema } from './objects/FinancialTransactionSumAggregateInput.schema';

export const FinancialTransactionGroupBySchema: z.ZodType<Prisma.FinancialTransactionGroupByArgs> = z.object({ where: FinancialTransactionWhereInputObjectSchema.optional(), orderBy: z.union([FinancialTransactionOrderByWithAggregationInputObjectSchema, FinancialTransactionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: FinancialTransactionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(FinancialTransactionScalarFieldEnumSchema), _count: z.union([ z.literal(true), FinancialTransactionCountAggregateInputObjectSchema ]).optional(), _min: FinancialTransactionMinAggregateInputObjectSchema.optional(), _max: FinancialTransactionMaxAggregateInputObjectSchema.optional(), _avg: FinancialTransactionAvgAggregateInputObjectSchema.optional(), _sum: FinancialTransactionSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.FinancialTransactionGroupByArgs>;

export const FinancialTransactionGroupByZodSchema = z.object({ where: FinancialTransactionWhereInputObjectSchema.optional(), orderBy: z.union([FinancialTransactionOrderByWithAggregationInputObjectSchema, FinancialTransactionOrderByWithAggregationInputObjectSchema.array()]).optional(), having: FinancialTransactionScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(FinancialTransactionScalarFieldEnumSchema), _count: z.union([ z.literal(true), FinancialTransactionCountAggregateInputObjectSchema ]).optional(), _min: FinancialTransactionMinAggregateInputObjectSchema.optional(), _max: FinancialTransactionMaxAggregateInputObjectSchema.optional(), _avg: FinancialTransactionAvgAggregateInputObjectSchema.optional(), _sum: FinancialTransactionSumAggregateInputObjectSchema.optional() }).strict();